name: Build PDF

on:
  push:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: '2'
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      - run: nix-channel --update
      - run: ./pdf.sh
      - name: Store pdf
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: |
            *.pdf
